version: 2.1

jobs:
  checkout-org-context:
    docker:
      - image: cimg/base:stable
    resource_class:
    steps:
      - checkout
      - run: |
          # refreshing the permissions of ktwl41 still did not trigger.
          # will try removing the org context requirements.
          cat README.md
      - run: |
          # should fail; no such env var injected
          printenv FORK

workflows:
  main:
    jobs:
      - checkout-org-context
