version: 2.1

jobs:
  checkout-org-context:
    docker:
      - image: cimg/base:stable
    resource_class:
    steps:
      - checkout
      - run: |
          # turned out the last commit still did not trigger;
          # ktwl41 is not allowed to use the kelvintaywl-cci/spoon-and-fork org context, despite being a member of kelvintaywl-cci/chef team
          # I have reverted the org context's security group to ALL_MEMBERS now.
          # Expecting this to trigger now.
          cat README.md
      - run: |
          # check out the org context!
          # should print 'spoon'
          printenv FORK

workflows:
  main:
    jobs:
      - checkout-org-context:
          context:
            # this org context is available for ALL_MEMBERS
            - spoon-and-fork
