version: 2.1

jobs:
  checkout-org-context:
    docker:
      - image: cimg/base:stable
    resource_class:
    steps:
      - checkout
      - run: |
          # earlier commit did not trigger again.
          # explicitly made ktwl41 refresh permissions on CircleCI UI now.
          # hoping this triggers now.
          cat README.md
      - run: |
          # check out the org context!
          # should print 'spoon'
          printenv FORK

workflows:
  main:
    jobs:
      - checkout-org-context:
          context:
            # this org context is available for ALL_MEMBERS
            - spoon-and-fork
