version: 2.1

jobs:
  checkout-org-context:
    docker:
      - image: cimg/base:stable
    resource_class:
    steps:
      - checkout
      - run: |
          # now, ktwl41 has been invited to the kelvintaywl-cci/chef team.
          # this time, this commit should trigger, since ktwl41 is also following the main project.
          cat README.md
      - run: |
          # check out the org context!
          # should print 'spoon'
          printenv FORK

workflows:
  main:
    jobs:
      - checkout-org-context:
          context:
            # this org context is available for kelvintaywl-cci/chef team only
            - spoon-and-fork
