version: 2.1

jobs:
  checkout-org-context:
    docker:
      - image: cimg/base:stable
    resource_class:
    steps:
      - checkout
      - run: |
          # ktwl41 is now invited to the original repo and has followed the main project
          # however, the org context has been limited to kelvintaywl-cci/chef team
          # which ktwl41 is not part of.
          cat README.md
      - run: |
          # check out the org context!
          # should print 'spoon'
          printenv FORK

workflows:
  main:
    jobs:
      - checkout-org-context:
          context:
            # this org context is available for kelvintaywl-cci/chef team only
            - spoon-and-fork
